name: Unit

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  teal_lua_consistency:
    name: Teal–Lua consistency
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ConorMacBride/install-package@v1
        with:
          apt: luarocks

      - name: Install Teal
        run: |
          sudo luarocks install tl

      - name: Build
        run: |
          ./addon/gen.sh

      - name: Check
        run: |
          git diff --color --exit-code
